spring:
  application:
    name: lab2-web-server

logging:
  level:
    es.unizar.webeng.lab2: INFO
    outbound-logs: INFO
    root: INFO

cors:
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000
